$schema: https://json-schema.org/draft/2020-12/schema
description: |
  A Research Object bundling resources and contextual information.
  Corresponds to ore:Aggregation from the OAI-ORE model.
  See: http://www.openarchives.org/ore/1.0/datamodel
type: object
properties:
  '@id':
    type: string
    format: uri
    description: Unique identifier for the research object
  id:
    type: string
    format: uri
    description: Unique identifier for the research object (alternative to @id)
  '@type':
    const: ResearchObject
    description: Type must be ResearchObject
  type:
    const: ResearchObject
    description: Type must be ResearchObject (alternative to @type)
  title:
    type: string
    description: Title of the research object
  description:
    type: string
    description: Description of the research object
  aggregates:
    type: array
    items:
      type: object
      properties:
        '@id':
          type: string
          format: uri
        id:
          type: string
          format: uri
    description: Resources aggregated in this research object
  manifest:
    type: string
    format: uri
    description: The manifest describing this research object
  created:
    type: string
    format: date-time
    description: Creation date of the research object
anyOf:
  - required: ['@id', '@type']
  - required: ['id', 'type']

